version: '3.8'

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/app/pb_data
      - ./pb_migrations:/app/pb_migrations
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@bookdirectstays.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-your-secure-password}
      - PB_DATA_DIR=/app/pb_data
      - PB_MIGRATIONS_DIR=/app/pb_migrations
      - PB_HOOKS_DIR=/app/pb_hooks
    networks:
      - pocketbase-network

  # Optional: Nginx reverse proxy for SSL/domain
  nginx:
    image: nginx:alpine
    container_name: pocketbase-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - pocketbase
    networks:
      - pocketbase-network

  # Optional: Database backup service
  backup:
    image: alpine:latest
    container_name: pocketbase-backup
    restart: unless-stopped
    volumes:
      - ./pb_data:/app/pb_data:ro
      - ./backups:/app/backups
    environment:
      - BACKUP_SCHEDULE=0 2 * * *  # Daily at 2 AM
    command: |
      sh -c '
        apk add --no-cache dcron
        echo "$$BACKUP_SCHEDULE cd /app && tar -czf /app/backups/backup-$$(date +%Y%m%d_%H%M%S).tar.gz pb_data" | crontab -
        crond -f
      '
    depends_on:
      - pocketbase
    networks:
      - pocketbase-network

networks:
  pocketbase-network:
    driver: bridge

volumes:
  pb_data:
  pb_migrations:
  backups: 